### ISSUE TITLE
Slower than deconvolution

### ISSUE THREAD

**Issue by LucyLu-LX** [IMG-PRCSNG/SubPixel#2]
I try to use the subpixel layer as an efficient way to replace deconvolution layer. 
However, the forward speed of subpixel layer (18ms) is way slower than the deconvolution layer(2 ms).
Any idea why this happened?
details:
input blobs: 1x4x540x960
deconvolution:  num_output: 1; kernel_size: 2; stride: 2; pad: 0

**Comment by LucyLu-LX** [comment]
It turns out that too many loops in subpixel layer due to the large size of input blobs.
Is there any other way to work around in numpy?

**Comment by IMG-PRCSNG** [comment]
I haven't benchmarked the run times. Thanks for pointing the need for it.

The code is CPU implementation and not GPU implementation. I just converted the code from https://github.com/tetrachrome/subpixel into something that can run in caffe. You can try running it with Intel optimized version of Python and Numpy as it would give you some speedup (I dont know by how much as I am yet to benchmark it). You can check it out [HERE](https://software.intel.com/en-us/distribution-for-python)

Also, if you are interested, You can consider porting the [original code](https://github.com/tetrachrome/subpixel) to pytorch or pycuda or equivalent GPU accelerated blas in python. PyTorch would be a recommended approach as it is almost a drop in replacement for numpy.

**Comment by LucyLu-LX** [comment]
I replaced these loops by numpy.transpose() and numpy.reshape(). Now the forward speed of subpixel layer could be reduced to 6ms.
Thanks for your advice. I will work on it.

**Comment by IMG-PRCSNG** [comment]
Let me know if you are willing to contribute back with your fix / findings. I can merge it. :)
